orderman/customers/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    CustomerListView,
    CustomerDetailView,
    CustomerCreateView,
    CustomerUpdateView,
)

urlpatterns = [
    url(
        r'^$',
        CustomerListView.as_view(),
        name='customer_list'
    ),
    url(
        r'^(?P<pk>[0-9]+)/$',
        CustomerDetailView.as_view(),
        name='customer_detail'
    ),
    url(
        r'^create/$',
        CustomerCreateView.as_view(),
        name='customer_create'
    ),
    url(
        r'^(?P<pk>[0-9]+)/update/$',
        CustomerUpdateView.as_view(),
        name='customer_update'
    ),
]

orderman/orders/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    OrderListView,
    OrderDetailView,
    OrderCreateView,
    OrderUpdateView,
    OrderItemListView,
    OrderItemDetailView,
    OrderItemCreateView,
    OrderItemUpdateView,
)

urlpatterns = [
    url(
        r'^$',
        OrderListView.as_view(),
        name='order_list'
    ), 
    url(
        r'^(?P<pk>[0-9]+)/$',
        OrderDetailView.as_view(),
        name='order_detail'
    ),
    url(
        r'^create/$',
        OrderCreateView.as_view(),
        name='order_create'
    ),
    url(
        r'^(?P<pk>[0-9]+)/update/$',
        OrderUpdateView.as_view(),
        name='order_update'
    ),
    url(
        r'^items/$',
        OrderItemListView.as_view(),
        name='orderitem_list'
    ), 
    url(
        r'^items/(?P<pk>[0-9]+)/$',
        OrderItemDetailView.as_view(),
        name='orderitem_detail'
    ),
    url(
        r'^items/create/$',
        OrderItemCreateView.as_view(),
        name='orderitem_create'
    ),
    url(
        r'^items/(?P<pk>[0-9]+)/update/$',
        OrderItemUpdateView.as_view(),
        name='orderitem_update'
    ),
]

orderman/products/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
)

urlpatterns = [
    url(
        r'^$',
        ProductListView.as_view(),
        name='product_list'
    ), 
    url(
        r'^(?P<pk>[0-9]+)/$',
        ProductDetailView.as_view(),
        name='product_detail'
    ),
    url(
        r'^create/$',
        ProductCreateView.as_view(),
        name='product_create'
    ),
    url(
        r'^(?P<pk>[0-9]+)/update/$',
        ProductUpdateView.as_view(),
        name='product_update'
    ),
]

orderman/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^customers/', include('orderman.customers.urls', namespace="customers")),
    url(r'^products/', include('orderman.products.urls', namespace="products")),
    url(r'^orders/', include('orderman.orders.urls', namespace="orders")),
]

orderman/customers/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Customer(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    phone = models.CharField(max_length=20)

    def __unicode__(self):
        return self.name

orderman/orders/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here

class Order(models.Model):
    customer = models.ForeignKey('customers.Customer', related_name='order')
    order_date = models.DateField(blank=False, null=False)
    collection_date = models.DateField(blank=False, null=False)
    method = models.CharField(max_length=250, blank=True, null=True)
    status = models.CharField(max_length=250, blank=True, null=True)
    location = models.CharField(max_length=250, blank=True, null=True)
    ticket_number = models.PositiveIntegerField(blank=False, null=False)

    def __unicode__(self):
        return 'OR-%06d' % (self.pk)

class OrderItem(models.Model):
    product = models.ForeignKey('products.Product', related_name='order_item')
    price = models.PositiveIntegerField(blank=False, null=False)
    order = models.ForeignKey('orders.Order', related_name='order_item')
    quantity = models.PositiveIntegerField(default=1)
    order_date = models.DateField(blank=False, null=False)

    def __unicode__(self):
        return '%s, OR-%06d, %s' % (self.product, self.order.id, self.order.customer)

orderman/products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=250)
    price = models.PositiveIntegerField(default=0)

    def __unicode__(self):
        return self.name

orderman/customers/forms.py
from django import forms

from .models import Customer

class CustomerForm(forms.ModelForm):
    
    class Meta:
        model = Customer
        fields = ('name', 'email', 'phone')

orderman/orders/forms.py
from django import forms

from .models import Order, OrderItem

class OrderForm(forms.ModelForm):
    
    class Meta:
        model = Order
        fields = (
            'customer',
            'collection_date',
            'order_date',
            'method',
            'status',
            'location',
            'ticket_number',
        )

class OrderItemForm(forms.ModelForm):

    class Meta:
        model = OrderItem
        fields = (
            'product',
            'price',
            'order',
            'quantity',
            'order_date',
        )

orderman/products/forms.py
from django import forms

from .models import Product 

class ProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = (
            'name',
            'price',
        )

orderman/customers/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse 
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .models import Customer
from .forms import CustomerForm


class CustomerListView(ListView):
    template_name = 'customers/customer_list.html'
    context_object_name = 'customers'

    def get_queryset(self):
        customers = Customer.objects.all()
        return customers

class CustomerDetailView(DetailView):
    model = Customer
    template_name = 'customers/customer_detail.html'

class CustomerCreateView(CreateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'customers/customer_add.html'

    def get_success_url(self):
        return reverse('customers:customer_list')

class CustomerUpdateView(UpdateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'customers/customer_update.html'

    def get_success_url(self):
        return reverse('customers:customer_list')

orderman/orders/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .models import Order, OrderItem
from .forms import OrderForm, OrderItemForm


class OrderListView(ListView):
    template_name = 'orders/order_list.html'
    context_object_name = 'orders'

    def get_queryset(self):
        orders = Order.objects.all()
        return orders

class OrderDetailView(DetailView):
    model = Order
    template_name = 'orders/order_detail.html'

class OrderCreateView(CreateView):
    model = Order
    form_class = OrderForm
    template_name = 'orders/order_add.html'

    def get_success_url(self):
        return reverse('orders:order_list')

class OrderUpdateView(UpdateView):
    model = Order
    form_class = OrderForm
    template_name = 'orders/order_update.html'

    def get_success_url(self):
        return reverse('orders:order_list')

class OrderItemListView(ListView):
    template_name = 'orders/order_item_list.html'
    context_object_name = 'order_items'

    def get_queryset(self):
        orderitems = OrderItem.objects.all()
        return orderitems

class OrderItemDetailView(DetailView):
    model = OrderItem
    template_name = 'orders/order_item_detail.html'

class OrderItemCreateView(CreateView):
    model = OrderItem
    form_class = OrderItemForm
    template_name = 'orders/order_item_add.html'

    def get_success_url(self):
        return reverse('orders:orderitem_list')

class OrderItemUpdateView(UpdateView):
    model = OrderItem
    form_class = OrderItemForm
    template_name = 'orders/order_item_update.html'

    def get_success_url(self):
        return reverse('orders:orderitem_list')

orderman/products/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .models import Product
from .forms import ProductForm


class ProductListView(ListView):
    template_name = 'products/product_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        products = Product.objects.all()
        return products

class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product_detail.html'

class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_add.html'

    def get_success_url(self):
        return reverse('products:product_list')

class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_update.html'

    def get_success_url(self):
        return reverse('products:product_list')

orderman/templates/products/product_add.html
{% extends 'base.html' %}

{% block title %}Add Product{% endblock title %}
{% block pageheader %}
    <h3>Add Product</h3>
{% endblock pageheader %}

{% block content %}
    <form class="form-horizontal" method="post">{% csrf_token %} 
        {{ form.as_p }}
        <div class="form-actions btn-group">
            <input class="btn btn-primary btn-sm" type="submit" name="save" value="Save Changes" />
            <a class="btn btn-secondary btn-sm" href="{% url 'products:product_list' %}">Cancel</a>
        </div>
    </form>
{% endblock content %}

orderman/templates/products/product_detail.html
{% extends 'base.html' %}

{% block title %}Product Detail{% endblock %}
{% block pageheader %}
    <h3>Product Detail</h3>
{% endblock pageheader %}

{% block content %}
    <dl>
        <dt>Product Name:</dt>
        <dd>{{ product.name }}</dd>
        <dt>Product Price:</dt>
        <dd>{{ product.price }}</dd>
    </dl>
{% endblock content %}

orderman/templates/products/product_list.html
{% extends 'base.html' %}

{% block title %}Product List{% endblock title %}
{% block pageheader %}
    <h3>Product List</h3>
    <a href="{% url 'products:product_create' %}" class="btn btn-dark btn-sm float-sm-right"><i class="fa fa-plus-square" aria-hidden="true"></i> Create Product</a>
{% endblock pageheader %}

{% block content %}
    {% if products %}
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Price</th>
                    <th class="actions"></th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.price }}</td>
                    <td class="actions">
                        <div class="btn btn-group">
                            <a href="{% url 'products:product_detail' product.id %}" class="btn btn-primary btn-sm"><i class="fa fa-search" aria-hidden="true"></i></a>
                            <a href="{% url 'products:product_update' product.id %}" class="btn btn-danger btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

orderman/templates/products/product_update.html
{% extends 'base.html' %}

{% block title %}Update Product{% endblock title %}
{% block pageheader %}
    <h3>Update Product</h3>
{% endblock pageheader %}

{% block content %}
    <form class="form-horizontal" method="post">{% csrf_token %} 
        {{ form.as_p }}
        <div class="form-actions btn-group">
            <input class="btn btn-primary btn-sm" type="submit" name="save" value="Save Changes" />
            <a class="btn btn-secondary btn-sm" href="{% url 'products:product_list' %}">Cancel</a>
        </div>
    </form>
{% endblock content %}